name: StatusPageMSPTMonitor
version: '${project.version}'
main: dev.goldenedit.statuspagemsptmonitor.StatusPageMSPTMonitor
api-version: 1.20
commands:
  reloadstatuspage:
    description: Reloads the StatusPageMSPTMonitor configuration
permissions:
  statuspage.reload:
    description: Allows reloading of StatusPageMSPTMonitor configuration
    default: op